# Generated by Django 5.1.6 on 2025-03-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resources')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.tag')),
            ],
        ),
        migrations.AddField(
            model_name='resources',
            name='tags',
            field=models.ManyToManyField(through='resources.ResourcesTag', to='resources.tag'),
        ),
        migrations.AddConstraint(
            model_name='resourcestag',
            constraint=models.UniqueConstraint(fields=('resources', 'tag'), name='resource_tag_unique', violation_error_message='Tag already exist for resource'),
        ),
    ]
