# Generated by Django 5.1.6 on 2025-03-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resources_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name_plural': 'Resources'},
        ),
    ]
