# Generated by Django 5.1.6 on 2025-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('user_info', models.TextField()),
                ('age', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
