# Generated by Django 5.1.6 on 2025-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_info2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_info',
            field=models.TextField(default=''),
        ),
    ]
