# Generated by Django 5.1.6 on 2025-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(default='')),
                ('user_info', models.TextField(default='')),
                ('age', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_info2', models.TextField(default='')),
            ],
        ),
    ]
