# Generated by Django 5.1.6 on 2025-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name', 'age']},
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name', 'age'], name='user_name_5216d9_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
