# Generated by Django 5.1.6 on 2025-02-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='user',
        ),
    ]
