# Generated by Django 5.1.6 on 2025-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(max_length=400)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='female', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('number_of_awards', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('Science', 'SCIENCE'), ('ScienceFiction', 'SCIENCEFICTION'), ('Religious', 'RELIGIOUS'), ('Art', 'ART'), ('General', 'GENERAL')], default='General', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
