# Generated by Django 5.1.6 on 2025-02-27 20:24

import apps.bookstore.my_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='number_of_awards',
            field=models.PositiveSmallIntegerField(default=0, validators=[apps.bookstore.my_validators.maximun_no_of_awards]),
        ),
    ]
