# Generated by Django 5.1.6 on 2025-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
