name: Django Project on Users Resources and BookStore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install Dependencies and Libraries
        run: | 
          pip install -r requirements/dev.txt
      
      - name: Run our Unit Test
        run: |
          make dev-test2
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
